---
# Running MicroK8s on some ARM hardware may run into difficulties
# because cgroups (required!) are not enabled by default. This
# can be remedied on the Rasberry Pi.
# https://microk8s.io/docs/install-alternatives#heading--arm

- name: Check if /boot/firmware/cmdline.txt exists
  ansible.builtin.stat:
    path: /boot/firmware/cmdline.txt
  register: microk8s_boot_config
  tags:
    - microk8s
    - microk8s.dependencies
    - microk8s.dependencies.cgroups

- name: Slurp /boot/firmware/cmdline.txt
  ansible.builtin.slurp:
    src: /boot/firmware/cmdline.txt
  register: microk8s_boot_config_content
  when:
    - microk8s_boot_config.stat.exists
  tags:
    - microk8s
    - microk8s.dependencies
    - microk8s.dependencies.cgroups

- name: Enable cgroups in /boot/firmware/cmdline.txt
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*)'
    line: '{{ microk8s_cgroup_opt }} \1'
    backrefs: true
  with_items:
    - "cgroup_enable=memory"
    - "cgroup_memory=1"
  loop_control:
    loop_var: microk8s_cgroup_opt
    label: "{{ microk8s_cgroup_opt }}"
  register: microk8s_update_boot_config
  notify: Reboot System
  when:
    - microk8s_boot_config.stat.exists
    - microk8s_cgroup_opt not in
      (microk8s_boot_config_content['content'] | b64decode)
  tags:
    - microk8s
    - microk8s.dependencies
    - microk8s.dependencies.cgroups

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
...
